// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: packet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHash      uint64                 `protobuf:"varint,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`          // Unique file / session ID
	BlockId       uint32                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`             // Index of the large block (0, 1, 2...)
	TotalBlocks   uint32                 `protobuf:"varint,3,opt,name=total_blocks,json=totalBlocks,proto3" json:"total_blocks,omitempty"` // Total blocks in the full file
	SymbolId      uint32                 `protobuf:"varint,4,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`          // Packet index (0 to K-1 for data, K to N-1 for parity)
	KSymbols      uint32                 `protobuf:"varint,5,opt,name=k_symbols,json=kSymbols,proto3" json:"k_symbols,omitempty"`          // Number of source data packets (e.g., 200)
	NSymbols      uint32                 `protobuf:"varint,6,opt,name=n_symbols,json=nSymbols,proto3" json:"n_symbols,omitempty"`          // Total packets transmitted (K data + M parity, e.g., 260)
	FileSize      uint64                 `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`          // Full original file size in bytes (for padding truncation)
	Content       []byte                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`                             // Raw binary payload (< 1400 bytes)
	PacketCrc     uint32                 `protobuf:"varint,9,opt,name=packet_crc,json=packetCrc,proto3" json:"packet_crc,omitempty"`       // CRC32 checksum to detect bit flips before FEC decoding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetFileHash() uint64 {
	if x != nil {
		return x.FileHash
	}
	return 0
}

func (x *Packet) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *Packet) GetTotalBlocks() uint32 {
	if x != nil {
		return x.TotalBlocks
	}
	return 0
}

func (x *Packet) GetSymbolId() uint32 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

func (x *Packet) GetKSymbols() uint32 {
	if x != nil {
		return x.KSymbols
	}
	return 0
}

func (x *Packet) GetNSymbols() uint32 {
	if x != nil {
		return x.NSymbols
	}
	return 0
}

func (x *Packet) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Packet) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Packet) GetPacketCrc() uint32 {
	if x != nil {
		return x.PacketCrc
	}
	return 0
}

var File_packet_proto protoreflect.FileDescriptor

const file_packet_proto_rawDesc = "" +
	"\n" +
	"\fpacket.proto\x12\auniflow\"\x90\x02\n" +
	"\x06Packet\x12\x1b\n" +
	"\tfile_hash\x18\x01 \x01(\x04R\bfileHash\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\rR\ablockId\x12!\n" +
	"\ftotal_blocks\x18\x03 \x01(\rR\vtotalBlocks\x12\x1b\n" +
	"\tsymbol_id\x18\x04 \x01(\rR\bsymbolId\x12\x1b\n" +
	"\tk_symbols\x18\x05 \x01(\rR\bkSymbols\x12\x1b\n" +
	"\tn_symbols\x18\x06 \x01(\rR\bnSymbols\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x04R\bfileSize\x12\x18\n" +
	"\acontent\x18\b \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"packet_crc\x18\t \x01(\rR\tpacketCrcB\x06Z\x04./pbb\x06proto3"

var (
	file_packet_proto_rawDescOnce sync.Once
	file_packet_proto_rawDescData []byte
)

func file_packet_proto_rawDescGZIP() []byte {
	file_packet_proto_rawDescOnce.Do(func() {
		file_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)))
	})
	return file_packet_proto_rawDescData
}

var file_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packet_proto_goTypes = []any{
	(*Packet)(nil), // 0: uniflow.Packet
}
var file_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packet_proto_init() }
func file_packet_proto_init() {
	if File_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packet_proto_rawDesc), len(file_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packet_proto_goTypes,
		DependencyIndexes: file_packet_proto_depIdxs,
		MessageInfos:      file_packet_proto_msgTypes,
	}.Build()
	File_packet_proto = out.File
	file_packet_proto_goTypes = nil
	file_packet_proto_depIdxs = nil
}
