// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: tx-ipc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SenderState int32

const (
	SenderState_IDLE    SenderState = 0
	SenderState_WORKING SenderState = 1
)

// Enum value maps for SenderState.
var (
	SenderState_name = map[int32]string{
		0: "IDLE",
		1: "WORKING",
	}
	SenderState_value = map[string]int32{
		"IDLE":    0,
		"WORKING": 1,
	}
)

func (x SenderState) Enum() *SenderState {
	p := new(SenderState)
	*p = x
	return p
}

func (x SenderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SenderState) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_ipc_proto_enumTypes[0].Descriptor()
}

func (SenderState) Type() protoreflect.EnumType {
	return &file_tx_ipc_proto_enumTypes[0]
}

func (x SenderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SenderState.Descriptor instead.
func (SenderState) EnumDescriptor() ([]byte, []int) {
	return file_tx_ipc_proto_rawDescGZIP(), []int{0}
}

// TX File Monitor -> TX Sender
type TaskAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileHash      uint64                 `protobuf:"varint,2,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"` // Sent to RX for final integrity validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAssignment) Reset() {
	*x = TaskAssignment{}
	mi := &file_tx_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAssignment) ProtoMessage() {}

func (x *TaskAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_tx_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAssignment.ProtoReflect.Descriptor instead.
func (*TaskAssignment) Descriptor() ([]byte, []int) {
	return file_tx_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *TaskAssignment) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *TaskAssignment) GetFileHash() uint64 {
	if x != nil {
		return x.FileHash
	}
	return 0
}

// TX File Monitor -> TX Sender
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_tx_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_tx_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_tx_ipc_proto_rawDescGZIP(), []int{1}
}

// TX Sender -> TX File Monitor
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SenderState            `protobuf:"varint,1,opt,name=state,proto3,enum=uniflow.SenderState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_tx_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tx_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_tx_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetState() SenderState {
	if x != nil {
		return x.State
	}
	return SenderState_IDLE
}

var File_tx_ipc_proto protoreflect.FileDescriptor

const file_tx_ipc_proto_rawDesc = "" +
	"\n" +
	"\ftx-ipc.proto\x12\auniflow\"J\n" +
	"\x0eTaskAssignment\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_hash\x18\x02 \x01(\x04R\bfileHash\"\x06\n" +
	"\x04Ping\"7\n" +
	"\tHeartbeat\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.uniflow.SenderStateR\x05state*$\n" +
	"\vSenderState\x12\b\n" +
	"\x04IDLE\x10\x00\x12\v\n" +
	"\aWORKING\x10\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_tx_ipc_proto_rawDescOnce sync.Once
	file_tx_ipc_proto_rawDescData []byte
)

func file_tx_ipc_proto_rawDescGZIP() []byte {
	file_tx_ipc_proto_rawDescOnce.Do(func() {
		file_tx_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_ipc_proto_rawDesc), len(file_tx_ipc_proto_rawDesc)))
	})
	return file_tx_ipc_proto_rawDescData
}

var file_tx_ipc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tx_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tx_ipc_proto_goTypes = []any{
	(SenderState)(0),       // 0: uniflow.SenderState
	(*TaskAssignment)(nil), // 1: uniflow.TaskAssignment
	(*Ping)(nil),           // 2: uniflow.Ping
	(*Heartbeat)(nil),      // 3: uniflow.Heartbeat
}
var file_tx_ipc_proto_depIdxs = []int32{
	0, // 0: uniflow.Heartbeat.state:type_name -> uniflow.SenderState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tx_ipc_proto_init() }
func file_tx_ipc_proto_init() {
	if File_tx_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_ipc_proto_rawDesc), len(file_tx_ipc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_ipc_proto_goTypes,
		DependencyIndexes: file_tx_ipc_proto_depIdxs,
		EnumInfos:         file_tx_ipc_proto_enumTypes,
		MessageInfos:      file_tx_ipc_proto_msgTypes,
	}.Build()
	File_tx_ipc_proto = out.File
	file_tx_ipc_proto_goTypes = nil
	file_tx_ipc_proto_depIdxs = nil
}
