# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tipc.proto\x12\x07uniflow\"\xea\x01\n\x0eTaskAssignment\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\x11\n\tfile_hash\x18\x03 \x01(\x04\x12\x11\n\tfile_size\x18\x04 \x01(\x04\x12\x14\n\x0ctotal_blocks\x18\x05 \x01(\r\x12\x11\n\tk_symbols\x18\x06 \x01(\r\x12\x11\n\tn_symbols\x18\x07 \x01(\r\x12\x13\n\x0bsymbol_size\x18\x08 \x01(\r\x12\x17\n\x0f\x61ssigned_blocks\x18\t \x03(\r\x12\"\n\x04mode\x18\n \x01(\x0e\x32\x14.uniflow.SessionMode*1\n\x0bSessionMode\x12\x11\n\rSINGLE_SENDER\x10\x00\x12\x0f\n\x0b\x44ISTRIBUTED\x10\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SESSIONMODE']._serialized_start=259
  _globals['_SESSIONMODE']._serialized_end=308
  _globals['_TASKASSIGNMENT']._serialized_start=23
  _globals['_TASKASSIGNMENT']._serialized_end=257
# @@protoc_insertion_point(module_scope)
