# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tx-ipc.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tx-ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctx-ipc.proto\x12\x07uniflow\"6\n\x0eTaskAssignment\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x11\n\tfile_hash\x18\x02 \x01(\x04\"\x06\n\x04Ping\"0\n\tHeartbeat\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.uniflow.SenderState*$\n\x0bSenderState\x12\x08\n\x04IDLE\x10\x00\x12\x0b\n\x07WORKING\x10\x01\x42\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tx_ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_SENDERSTATE']._serialized_start=139
  _globals['_SENDERSTATE']._serialized_end=175
  _globals['_TASKASSIGNMENT']._serialized_start=25
  _globals['_TASKASSIGNMENT']._serialized_end=79
  _globals['_PING']._serialized_start=81
  _globals['_PING']._serialized_end=87
  _globals['_HEARTBEAT']._serialized_start=89
  _globals['_HEARTBEAT']._serialized_end=137
# @@protoc_insertion_point(module_scope)
