// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: rx-ipc.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymbolBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    uint32                 `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Packets       []*Packet           `protobuf:"bytes,2,rep,name=packets,proto3" json:"packets,omitempty"` // max 30, flushed every 100ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolBatch) Reset() {
	*x = SymbolBatch{}
	mi := &file_rx_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolBatch) ProtoMessage() {}

func (x *SymbolBatch) ProtoReflect() protoreflect.Message {
	mi := &file_rx_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolBatch.ProtoReflect.Descriptor instead.
func (*SymbolBatch) Descriptor() ([]byte, []int) {
	return file_rx_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolBatch) GetReceiverId() uint32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SymbolBatch) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

var File_rx_ipc_proto protoreflect.FileDescriptor

const file_rx_ipc_proto_rawDesc = "" +
	"\n" +
	"\frx-ipc.proto\x12\auniflow\x1a\fpacket.proto\"Y\n" +
	"\vSymbolBatch\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\rR\n" +
	"receiverId\x12)\n" +
	"\apackets\x18\x02 \x03(\v2\x0f.uniflow.PacketR\apacketsb\x06proto3"

var (
	file_rx_ipc_proto_rawDescOnce sync.Once
	file_rx_ipc_proto_rawDescData []byte
)

func file_rx_ipc_proto_rawDescGZIP() []byte {
	file_rx_ipc_proto_rawDescOnce.Do(func() {
		file_rx_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rx_ipc_proto_rawDesc), len(file_rx_ipc_proto_rawDesc)))
	})
	return file_rx_ipc_proto_rawDescData
}

var file_rx_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rx_ipc_proto_goTypes = []any{
	(*SymbolBatch)(nil), // 0: uniflow.SymbolBatch
	(*Packet)(nil),   // 1: uniflow.Packet
}
var file_rx_ipc_proto_depIdxs = []int32{
	1, // 0: uniflow.SymbolBatch.packets:type_name -> uniflow.Packet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rx_ipc_proto_init() }
func file_rx_ipc_proto_init() {
	if File_rx_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rx_ipc_proto_rawDesc), len(file_rx_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rx_ipc_proto_goTypes,
		DependencyIndexes: file_rx_ipc_proto_depIdxs,
		MessageInfos:      file_rx_ipc_proto_msgTypes,
	}.Build()
	File_rx_ipc_proto = out.File
	file_rx_ipc_proto_goTypes = nil
	file_rx_ipc_proto_depIdxs = nil
}
