syntax = "proto3";

package uniflow;

option go_package = "./pb";

enum SessionMode {
  SINGLE_SENDER = 0;  // For files < 10MB
  DISTRIBUTED   = 1;  // For files 10MB-1GB
}

message TaskAssignment {
  // file access on local disk
  string file_path = 1;

  // global file parameters
  string file_name = 2;
  uint64 file_hash = 3;
  uint64 file_size = 4;

  //  FEC  parameters
  uint32 total_blocks = 5;
  uint32 k_symbols    = 6;
  uint32 n_symbols    = 7;
  uint32 symbol_size  = 8;

  // worker assignment
  repeated uint32 assigned_blocks = 9;
  SessionMode mode                = 10;
}