// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: rs-helper.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One shard actually received for a block. symbol_id uses the same
// numbering as Packet.symbol_id in packet.proto (0..k_symbols-1 = data,
// k_symbols..n_symbols-1 = parity).
type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolId      uint32                 `protobuf:"varint,1,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_rs_helper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_rs_helper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_rs_helper_proto_rawDescGZIP(), []int{0}
}

func (x *Shard) GetSymbolId() uint32 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

func (x *Shard) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// Session Manager -> rs_helper. file_hash/block_id are for rs_helper's own
// logging/correlation only — no part in the reconstruction math. Send only
// the shards actually received; anything omitted is treated as lost.
type ReconstructRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHash      uint64                 `protobuf:"varint,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	BlockId       uint32                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	KSymbols      uint32                 `protobuf:"varint,3,opt,name=k_symbols,json=kSymbols,proto3" json:"k_symbols,omitempty"`
	NSymbols      uint32                 `protobuf:"varint,4,opt,name=n_symbols,json=nSymbols,proto3" json:"n_symbols,omitempty"`
	Shards        []*Shard               `protobuf:"bytes,5,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconstructRequest) Reset() {
	*x = ReconstructRequest{}
	mi := &file_rs_helper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconstructRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconstructRequest) ProtoMessage() {}

func (x *ReconstructRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rs_helper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconstructRequest.ProtoReflect.Descriptor instead.
func (*ReconstructRequest) Descriptor() ([]byte, []int) {
	return file_rs_helper_proto_rawDescGZIP(), []int{1}
}

func (x *ReconstructRequest) GetFileHash() uint64 {
	if x != nil {
		return x.FileHash
	}
	return 0
}

func (x *ReconstructRequest) GetBlockId() uint32 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *ReconstructRequest) GetKSymbols() uint32 {
	if x != nil {
		return x.KSymbols
	}
	return 0
}

func (x *ReconstructRequest) GetNSymbols() uint32 {
	if x != nil {
		return x.NSymbols
	}
	return 0
}

func (x *ReconstructRequest) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

// rs_helper -> Session Manager.
type ReconstructResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                             // set when ok == false
	DataShards    [][]byte               `protobuf:"bytes,3,rep,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"` // k_symbols shards, in order, when ok == true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconstructResponse) Reset() {
	*x = ReconstructResponse{}
	mi := &file_rs_helper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconstructResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconstructResponse) ProtoMessage() {}

func (x *ReconstructResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rs_helper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconstructResponse.ProtoReflect.Descriptor instead.
func (*ReconstructResponse) Descriptor() ([]byte, []int) {
	return file_rs_helper_proto_rawDescGZIP(), []int{2}
}

func (x *ReconstructResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReconstructResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ReconstructResponse) GetDataShards() [][]byte {
	if x != nil {
		return x.DataShards
	}
	return nil
}

var File_rs_helper_proto protoreflect.FileDescriptor

const file_rs_helper_proto_rawDesc = "" +
	"\n" +
	"\x0frs-helper.proto\x12\auniflow\">\n" +
	"\x05Shard\x12\x1b\n" +
	"\tsymbol_id\x18\x01 \x01(\rR\bsymbolId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xae\x01\n" +
	"\x12ReconstructRequest\x12\x1b\n" +
	"\tfile_hash\x18\x01 \x01(\x04R\bfileHash\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\rR\ablockId\x12\x1b\n" +
	"\tk_symbols\x18\x03 \x01(\rR\bkSymbols\x12\x1b\n" +
	"\tn_symbols\x18\x04 \x01(\rR\bnSymbols\x12&\n" +
	"\x06shards\x18\x05 \x03(\v2\x0e.uniflow.ShardR\x06shards\"\\\n" +
	"\x13ReconstructResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1f\n" +
	"\vdata_shards\x18\x03 \x03(\fR\n" +
	"dataShardsB\x06Z\x04./pbb\x06proto3"

var (
	file_rs_helper_proto_rawDescOnce sync.Once
	file_rs_helper_proto_rawDescData []byte
)

func file_rs_helper_proto_rawDescGZIP() []byte {
	file_rs_helper_proto_rawDescOnce.Do(func() {
		file_rs_helper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rs_helper_proto_rawDesc), len(file_rs_helper_proto_rawDesc)))
	})
	return file_rs_helper_proto_rawDescData
}

var file_rs_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rs_helper_proto_goTypes = []any{
	(*Shard)(nil),               // 0: uniflow.Shard
	(*ReconstructRequest)(nil),  // 1: uniflow.ReconstructRequest
	(*ReconstructResponse)(nil), // 2: uniflow.ReconstructResponse
}
var file_rs_helper_proto_depIdxs = []int32{
	0, // 0: uniflow.ReconstructRequest.shards:type_name -> uniflow.Shard
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rs_helper_proto_init() }
func file_rs_helper_proto_init() {
	if File_rs_helper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rs_helper_proto_rawDesc), len(file_rs_helper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rs_helper_proto_goTypes,
		DependencyIndexes: file_rs_helper_proto_depIdxs,
		MessageInfos:      file_rs_helper_proto_msgTypes,
	}.Build()
	File_rs_helper_proto = out.File
	file_rs_helper_proto_goTypes = nil
	file_rs_helper_proto_depIdxs = nil
}
